### PR TITLE
Use site templates for CMS previews

### PR DESCRIPTION
**Pull request by erquhart**
- run Nunjucks client side to render accurate previews, live in the editor
- link to live previews for sites using compatible deployments

Screen Shot 2019-06-22 at 1 39 49 AM

### CODE REVIEW

**Comment by andybelldesign** [comment]
This looks great @erquhart, thank you! I’ll give it a proper look later 🙂

**Comment by andybelldesign** [comment]
I'm so glad you've added this @erquhart, thank you so much. I’d totally iceboxed admin previews because I couldn't get my head around it. It all makes total sense now after getting this PR, though 🎉

**Comment by erquhart** [comment]
We need a node lib to handle some of this, but the setup is usually pretty specific to the generator. The amazing thing about 11ty is it's use of is template languages, which all have compilers that can work on the client side, so you don't have to rewrite your templates in React, just precompute and map your data. Anyway, glad it worked out!

**Comment by andybelldesign** [comment]
Yeh that's yet another thing that's amazing about 11ty. This PR has totally transformed the editing experience, so big thanks again.

**Pull request merged**
